[package]
name = "activity-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true

[dependencies.web-sys]
version = "0.3.69"
features = ['console']
