[package]
name = "activity-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
wasm-bindgen-macro-support.workspace = true
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = "2.0.55"
