[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
activity = { path = "../../activity", version = "0.1.3" }
futures = "0.3.30"
rand = "0.8.5"
wasm-bindgen.workspace = true
yew = { version = "0.21.0", features = ["csr"] }
